### ISSUE TITLE
Missing zipped file

### ISSUE THREAD

**Issue by dbau** [twbattaglia/q2-summarizer#1]
Hi, 

I am trying to install q2-summarizer but I can't find the zip file https://github.com/twbattaglia/q2-summarizer/zipball/master.zip

I have downloaded the the repository as a zip file, but got the error:

> Could not find a version that satisfies the requirement qiime>=2.0.0 (from q2-summarizer==0.0.1) (from versions: 1.7.0.dev0, 1.8.0, 1.9.0, 1.9.1)
> No matching distribution found for qiime>=2.0.0 (from q2-summarizer==0.0.1)
> 

Thanks,
Davide

**Comment by twbattaglia** [comment]
Hey Davide, this repository was actually an experimental/testing ground to to develop a QIIME2 plugin. It was written with an much earlier version of QIIME v2, so I do not think it will work with the latest version.

Apologies for the confusion.

Tom
